---

stages:
  - build
  - deploy

cache:
  paths:
    - .m2/repository/

build:
  stage: build
  image: maven:3.6.3-jdk-11-slim
  except:
    - tags
  variables:
    MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
    MAVEN_OPTS: -Dmaven.repo.local=.m2/repository
  script:
    - mvn clean install
  artifacts:
    paths:
      - target

pages:
  stage: deploy
  image: alpine
  only:
    refs:
      - master
  except:
    - tags
  script:
    - mv target/site public
  artifacts:
    paths:
      - public
      - target/*.jar
